version: "3.8"
services:
  api:
    container_name: nginx
    image: nginx:1.17
    restart: always
    env_file: .env
    depends_on:
      - php
    links:
      - php
    volumes:
      - ${APP_PATH}:/var/www/html
      - ${HOME}/.aws/credentials:/var/www/.aws/credentials
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - cachedata:/var/www/html/var/cache
    ports:
      - "80:80"
    networks:
      - default

  php:
    build:
      context: ./php
    restart: always
    env_file: .env
    working_dir: /var/www/html
    volumes:
      - ${APP_PATH}:/var/www/html
      - ${HOME}/.aws/credentials:/var/www/.aws/credentials
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - "9000"

  postgresql:
    image: postgres:12.3
    container_name: postgresql
    env_file: .env
    restart: always
    command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
    ports:
        - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  assets:
    build:
      context: ./assets
    env_file: .env
    volumes:
      - ${APP_PATH}/.nvmrc:/.nvmrc
      - ${APP_PATH}/package.json:/package.json
      - ${APP_PATH}/bower.json:/bower.json
      - ${HOME}/.npm:/.npm
    command: "npm install && bower install && node_modules/grunt/bin/grunt"

  mailhog:
    image: mailhog/mailhog
    ports:
        - "1025:1025"
        - "8025:8025"

  redis:
    image: redis:5.0.7
    hostname: redis
    volumes:
      - "redisdata:/data"

  composer:
    image: composer:1.10
    working_dir: /var/www/html
    env_file: .env
    environment:
      SSH_AUTH_SOCK: /ssh-auth.sock
    volumes:
      - ${APP_PATH}:/var/www/html
      - "$SSH_AUTH_SOCK:/ssh-auth.sock"
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: composer install --ignore-platform-reqs --no-scripts

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
      - "elasticdata:/usr/share/elasticsearch/data"

volumes:
  cachedata:
  dbdata:
  redisdata:
  elasticdata:
