version: "3.8"

services:

### AWS EB-CLI ################################################
  aws:
    build:
      context: ./aws-cli
    env_file: .env
    volumes:
      - ${AWS_CREDENTIALS_HOME}/.aws:/root/.aws:ro
    tty: true

  nextjs:
    build:
      context: ./nextjs
    ports:
      - "3000:3000"
    container_name: nextjs-ui
    restart: always
    working_dir: ${APP_CODE_PATH_CONTAINER}
    stdin_open: true
    tty: true
    volumes:
       - ${FRONTEND_APP_PATH}:${APP_CODE_PATH_CONTAINER}
       - node_modules:${APP_CODE_PATH_CONTAINER}/node_modules

  nginx:
    container_name: apidev.viddyoze.com
    image: nginx:1.17
    restart: always
    env_file: .env
    depends_on:
      - php
    links:
      - php
    volumes:
      - ${BACKEND_APP_PATH}/app:${APP_CODE_PATH_CONTAINER}/app${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/assets:${APP_CODE_PATH_CONTAINER}/assets${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/bin:${APP_CODE_PATH_CONTAINER}/bin${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/src:${APP_CODE_PATH_CONTAINER}/src${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/web:${APP_CODE_PATH_CONTAINER}/web${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/tmp:${APP_CODE_PATH_CONTAINER}/tmp${APP_CODE_CONTAINER_FLAG}
      - vendordata:${APP_CODE_PATH_CONTAINER}/vendor
      - cachedata:${APP_CODE_PATH_CONTAINER}/var
      - ${AWS_CREDENTIALS_HOME}/.aws:/root/.aws:ro
      - ${AWS_CREDENTIALS_HOME}/.aws:/var/www/.aws:ro
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    ports:
      - "80:80"

  assets:
    build:
      context: ./node
    container_name: node
    env_file: .env
    working_dir: ${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${BACKEND_APP_PATH}/assets:${APP_CODE_PATH_CONTAINER}/assets${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/web:${APP_CODE_PATH_CONTAINER}/web${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/package.json:${APP_CODE_PATH_CONTAINER}/package.json:ro
      - ${BACKEND_APP_PATH}/bower.json:${APP_CODE_PATH_CONTAINER}/bower.json:ro
      - ${BACKEND_APP_PATH}/Gruntfile.js:${APP_CODE_PATH_CONTAINER}/Gruntfile.js:ro
      - nodedata:${APP_CODE_PATH_CONTAINER}/node_modules
      - bowerdata:${APP_CODE_PATH_CONTAINER}/bower_components
    command: "node_modules/grunt/bin/grunt watch"
    stdin_open: true
    tty: true

  php:
    container_name: php
    build:
      context: ./php
    restart: always
    env_file: .env
    working_dir: ${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${BACKEND_APP_PATH}/app:${APP_CODE_PATH_CONTAINER}/app${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/assets:${APP_CODE_PATH_CONTAINER}/assets${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/bin:${APP_CODE_PATH_CONTAINER}/bin${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/src:${APP_CODE_PATH_CONTAINER}/src${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/web:${APP_CODE_PATH_CONTAINER}/web${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/tmp:${APP_CODE_PATH_CONTAINER}/tmp${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/tests:${APP_CODE_PATH_CONTAINER}/tests${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/phpunit.xml:${APP_CODE_PATH_CONTAINER}/phpunit.xml:ro
      - ${BACKEND_APP_PATH}/composer.json:${APP_CODE_PATH_CONTAINER}/composer.json
      - ${BACKEND_APP_PATH}/composer.lock:${APP_CODE_PATH_CONTAINER}/composer.lock
      - vendordata:${APP_CODE_PATH_CONTAINER}/vendor
      - cachedata:${APP_CODE_PATH_CONTAINER}/var
      - ${AWS_CREDENTIALS_HOME}/.aws:/root/.aws:ro
      - ${AWS_CREDENTIALS_HOME}/.aws:/var/www/.aws:ro
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./php/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      #- ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      #- ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:ro
    expose:
      - "9000"

  rendering:
    container_name: rendering
    build:
      context: ${BACKEND_APP_PATH}
    volumes:
      - ${AWS_CREDENTIALS_HOME}/.aws:/root/.aws:ro
      - ${AWS_CREDENTIALS_HOME}/.aws:${WORKER_CODE_PATH_CONTAINER}/.aws:ro
      - ${BACKEND_APP_PATH}/tmp/images:${WORKER_CODE_PATH_CONTAINER}/tmp/images${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/app/Resources/templates:${WORKER_CODE_PATH_CONTAINER}/app/Resources/templates${APP_CODE_CONTAINER_FLAG}
    env_file: .env
    environment:
      DOCKER_DEFAULT_PLATFORM: ${DOCKER_DEFAULT_PLATFORM}
    depends_on:
      - postgresql
    command: ['/usr/bin/env', 'bash', './bin/process_render_queue']

  keyframe-rendering:
    container_name: keyframe-rendering
    build:
      context: ${BACKEND_APP_PATH}
    volumes:
      - ${AWS_CREDENTIALS_HOME}/.aws:/root/.aws:ro
      - ${AWS_CREDENTIALS_HOME}/.aws:${WORKER_CODE_PATH_CONTAINER}/.aws:ro
      - ${BACKEND_APP_PATH}/tmp/images:${WORKER_CODE_PATH_CONTAINER}/tmp/images${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/app/Resources/templates:${WORKER_CODE_PATH_CONTAINER}/app/Resources/templates${APP_CODE_CONTAINER_FLAG}
    env_file: .env
    command: ['/usr/bin/env', 'bash', './bin/process_keyframe_preview_queue']

  phpunit:
    build:
      context: ./phpunit
    env_file: .env
    working_dir: ${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${BACKEND_APP_PATH}/app:${APP_CODE_PATH_CONTAINER}/app${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/src:${APP_CODE_PATH_CONTAINER}/src${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/web:${APP_CODE_PATH_CONTAINER}/web${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/tests:${APP_CODE_PATH_CONTAINER}/tests${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/phpunit.xml:${APP_CODE_PATH_CONTAINER}/phpunit.xml:ro
      - vendordata:${APP_CODE_PATH_CONTAINER}/vendor
      - cachedata:${APP_CODE_PATH_CONTAINER}/var
    tty: true
    stdin_open: true

  postgresql:
    image: postgres:12.3
    container_name: postgresql
    env_file: .env
    restart: always
    command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${DATA_PATH_HOST}/postgresql:/var/lib/postgresql/data

  ### pgAdmin ##############################################
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ${DATA_PATH_HOST}/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql

  mailhog:
    image: mailhog/mailhog
    ports:
        - "1025:1025"
        - "8025:8025"

### SQS #############################################
  sqs:
    build: ./sqs
    ports:
      - "${SQS_NODE_HOST_PORT}:9324"
      - "${SQS_MANAGEMENT_HTTP_HOST_PORT}:9325"
    privileged: true
    hostname: viddyoze-sqs
    volumes:
      - ${DATA_PATH_HOST}/sqs:/opt/custom

### Minio ################################################
  minio:
    build: ./minio
    volumes:
      - ${DATA_PATH_HOST}/minio/data:/export
      - ${DATA_PATH_HOST}/minio/config:/root/.minio
    ports:
      - "${MINIO_PORT}:9000"
    environment:
      - MINIO_ACCESS_KEY=access
      - MINIO_SECRET_KEY=secretkey

  redis:
    image: redis:5.0.7
    hostname: redis
    volumes:
      - "${DATA_PATH_HOST}/redis:/data"

  composer:
    image: composer:1.10
    working_dir: ${APP_CODE_PATH_CONTAINER}
    env_file: .env
    environment:
      SSH_AUTH_SOCK: /ssh-auth.sock
      COMPOSER_MEMORY_LIMIT: 1
    volumes:
      - ${BACKEND_APP_PATH}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${BACKEND_APP_PATH}/composer.json:${APP_CODE_PATH_CONTAINER}/composer.json:delegated
      - ${BACKEND_APP_PATH}/composer.lock:${APP_CODE_PATH_CONTAINER}/composer.lock:delegated
      - vendordata:${APP_CODE_PATH_CONTAINER}/vendor
      - "$SSH_AUTH_SOCK:/ssh-auth.sock"
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: composer install --no-cache --ignore-platform-reqs --no-scripts
    tty: true
    stdin_open: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
      - "elasticdata:/usr/share/elasticsearch/data"

## Certbot #########################################
  certbot:
    build:
      context: ./certbot
    volumes:
      - ./data/certbot/certs/:/var/certs
      - ./certbot/letsencrypt/:/var/www/letsencrypt
    environment:
      - CN="apidev.viddyoze.com"
      - EMAIL="fake.email@gmail.com"

## SWAGGER EDITOR ############################################
  swagger-editor:
    build: ./swagger-editor
    ports:
      - ${SWAGGER_EDITOR_PORT}:8080

### SWAGGER UI ################################################
  swagger-ui:
    build: ./swagger-ui
    environment:
      - API_URL=${SWAGGER_API_URL}
    ports:
      - ${SWAGGER_UI_PORT}:8080

volumes:
  node_modules:
    driver: ${VOLUMES_DRIVER}
  cachedata:
    driver: ${VOLUMES_DRIVER}
  vendordata:
    driver: ${VOLUMES_DRIVER}
  minio:
    driver: ${VOLUMES_DRIVER}
  elasticdata:
    driver: ${VOLUMES_DRIVER}
  nodedata:
    driver: ${VOLUMES_DRIVER}
  bowerdata:
    driver: ${VOLUMES_DRIVER}

networks:
  default:
    name: viddyoze